# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'weather' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for weather
  platform :ios, '8.0'
  
  #use_frameworks!  # <-- comment this out!
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native', :subspecs =>
    [
      'Core',
      'DevSupport',
    ]
  pod 'RNBackgroundGeolocation', :path => '../node_modules/react-native-background-geolocation'
  pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'

  target 'weather-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'weatherTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
